services:
  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - app_network

  yopass_app:
    build:
      context: ./yopass
      dockerfile: Dockerfile
    container_name: yopass_app
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - redis
    environment:
      - REDIS_CACHE_URL=redis://redis:6379

  selenium_browser:
    build:
      context: ./selenium_browser
      dockerfile: Dockerfile
    container_name: selenium_browser
    networks:
      - app_network
    depends_on:
      - yopass_app

networks:
  app_network:
    driver: bridge
