version: 2.1

global_context: &global_context
  context:
    - org-global

global_remote_docker: &global_remote_docker
  setup_remote_docker:
    docker_layer_caching: true
    version: docker23
global_dockerhub_auth: &global_dockerhub_auth
  auth:
    username: $GLOBAL_DOCKERHUB_USERNAME
    password: $GLOBAL_DOCKERHUB_PASSWORD
global_dockerhub_login: &global_dockerhub_login
  run:
    name: Authenticate with hub.docker.com - DockerHub
    command: docker login -u $GLOBAL_DOCKERHUB_USERNAME -p $GLOBAL_DOCKERHUB_PASSWORD

executors:
  docker-container:
    docker:
      - image: deliveroo/circleci:latest
        <<: *global_dockerhub_auth

jobs:
  build_docker_image:
    executor: docker-container
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - *global_remote_docker
      - *global_dockerhub_login
      - checkout
      - run:
          name: Docker build
          command: |
            docker build --tag "${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}" . \
            && docker save "${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}" \
              --output "/tmp/workspace/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}".tar
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - '*.tar'

  push_staging:
    executor: docker-container
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - *global_remote_docker
      - *global_dockerhub_login
      - run:
          name: Load docker image
          command: |
            docker load --input "/tmp/workspace/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}".tar
      - run:
          name: Push image to ECR
          command: |
            `print_env ${TARGET}`
            push_image_to_ecr
    environment:
      TARGET: staging

workflows:
  version: 2
  build:
    jobs:
      - build_docker_image:
          <<: *global_context
          filters:
            branches:
              only: staging
      - push_staging:
          <<: *global_context
          requires:
            - build_docker_image
          filters:
            branches:
              only: staging