version: 2

app:
  name: 'yopass'
  bootstrap: true
  environments:
    production:
      trackedBranch: 'master'
    staging:
      trackedBranch: 'staging'

plugins:
  - type: Hopper::Plugins::Terraform
    terraformRoot: "infrastructure/environments/{{ .hopper_environment }}"


services:
- type: Hopper::Services::ECS::Service
  name: web
  desiredCount: 1
  taskDefinition:
    containerDefinitions:
    - name: web
      cpu: 1024
      memory: 2048
      essential: true
      portMappings:
      - containerPort: 80

workflow:
  type: Hopper::Workflow::Flows::Basic
  name: roo-generate-workflow
  shardsToDeploy:
    - global
  actions:
    - type: Hopper::Workflow::Terraform::Run
      name: terraform_run
      runOrder: 1
    - type: Hopper::Workflow::Deployment::Services
      name: roo-generate deploy-step-1
      runOrder: 2
    - type: Hopper::Utils::SlackNotification
      name: roo-generate-deploying-slack-notification
      runOrder: 3
      channel: security-apps-rel
      text: |-
        :hourglass_flowing_sand: <{{ .hopper_release_link }}|Deploying> *{{ .app_name }}* to *{{ .hopper_environment }}* {{ .shard }} shard

        Triggered by {{ .release_creator }}
    - type: Hopper::Utils::SlackNotification
      name: roo-generate-deployed-slack-notification
      runOrder: 3
      channel: security-apps-rel
      text: ✅ *{{ .app_name }}* successfully <{{ .hopper_release_link }}|deployed> to *{{ .hopper_environment }}* {{ .shard }} shard
  onFailure:
    - type: Hopper::Utils::SlackNotification
      name: roo-generate-failure-slack-notification
      channel: security-apps-rel
      text: |-
        :x: *{{ .app_name }}* failed to <{{ .hopper_release_link }}|deploy> to *{{ .hopper_environment }}* {{ .failed_shard_name }} shard

        {{ .error_message }}
  onRollback:
    - type: Hopper::Utils::SlackNotification
      name: roo-generate-rollback-slack-notification
      channel: security-apps-rel
      text: ':hourglass_flowing_sand: *{{ .app_name }}* <{{ .hopper_release_link }}|rolling> back in *{{ .hopper_environment }}*'