version: 2

app:
  name: 'yopass'
  bootstrap: true
  environments:
    production:
      trackedBranch: 'master'
    staging:
      trackedBranch: 'staging'

plugins:
  - type: Hopper::Plugins::Terraform
    terraformRoot: "infrastructure/environments/{{ .hopper_environment }}"

services:
- type: Hopper::Services::ECS::Service
  name: web
  desiredCount: 1
  taskDefinition:
    containerDefinitions:
    - name: web
      cpu: 1024
      memory: 2048
      essential: true
      portMappings:
      - containerPort: 80

workflow:
  type: Hopper::Workflow::Flows::Basic
  name: roo-generate-workflow
  shardsToDeploy:
    - global
  actions:
    - type: Hopper::Workflow::Terraform::Run
      name: terraform_run
      runOrder: 1
    - type: Hopper::Workflow::Deployment::Services
      name: roo-generate deploy-step-1
      runOrder: 2

