version: "3.0"

services:
  memcached:
    image: memcached
    restart: always
    expose:
      - "11211"

  yopass:
    image: jhaals/yopass
    restart: always
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:9090:9090"
    environment:
      # listen address (default 0.0.0.0)
      # - YOPASS_ADDRESS
      # listen port (default 1337)
      - YOPASS_PORT=80
      # metrics server listen port (default -1)
      - YOPASS_METRICS_PORT=9090
      # max length of encrypted secret (default 10000)
      - YOPASS_MAX_LENGTH=100000
      # database backend ('memcached' or 'redis') (default "memcached")
      - YOPASS_DATABASE=memcached
      # Memcached address (default "localhost:11211")
      - YOPASS_MEMCACHED=localhost:11211
      # Redis URL (default "redis://localhost:6379/0")
      # - YOPASS_REDIS=redis://localhost:6379/0
      # path to TLS certificate
      # - YOPASS_TLS_CERT
      # path to TLS key
      # - YOPASS_TLS_KEY
