name: TEST sync master to staging branch

on:
  push:
    branches:
      - staging
  workflow_dispatch: # Allows manual triggering

jobs:
  syncStagingToMaster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the master branch
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Create a new branch from master
        run: git checkout -b staging-to-master

      - name: Merge Staging into the new branch
        run: git merge --no-ff origin/staging --allow-unrelated-histories || true

      - name: Revert changes to Dockerfile and .github
        run: |
          git checkout HEAD -- Dockerfile
          git checkout HEAD -- .github

      - name: Push changes to the new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin staging-to-master

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          branch: staging-to-master
          title: 'Sync Staging to Master'
          body: |
            This is an automated pull request to merge changes from the `staging` branch into the `master` branch.
