name: Sync with Upstream and Create PR

on:
  schedule:
    - cron: '35 9 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  sync-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/jhaals/yopass.git

      - name: Fetch upstream master
        run: git fetch upstream master

      - name: Check for changes in upstream master
        id: check_changes
        run: |
          git fetch upstream master
          if git diff --quiet HEAD..upstream/master; then
            echo "no changes"
            echo "{changes}={false}" >> $GITHUB_OUTPUT
          else
            echo "changes detected"
            echo "{changes}={true}" >> $GITHUB_OUTPUT
          fi

      - name: Sync with upstream master
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git checkout staging
          git merge --no-commit upstream/master
          git restore --source=HEAD --staged --worktree Dockerfile .github


      - name: Create Pull Request to master
        if: steps.check_changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Merge changes from upstream master [skip ci]"
          branch: sync-upstream-master
          base: master
          body: |
            This PR merges changes from the upstream YoPass master branch
          title: Merge changes from upstream master
          team-reviewers: deliveroo/security-eng
