name: Sync master with staging and Create PR

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  syncStagingToMain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Reset promotion branch
        run: |
          git fetch origin staging:staging
          git reset --hard staging
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: sync-staging-to-main
          title: 'Sync staging with master'
          body: |
            Staging branch was synced to upstream. This PR syncs the staging branch with the master branch for production deploy.
          team-reviewers: deliveroo/security-eng
          commit-message: 'Sync changes from staging to master [skip ci]'
          delete-branch: true